import Header from '@/components/Header'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Button, Container } from 'reactstrap'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">
            Digite uma frase e vamos analisar quantas palavras existem no nosso dicionário de hierarquias
          </h1>
          <p className="my-4">
            Você pode escolher qual a profundidade que deseja a contagem. <br /> Para ter uma ideia de quais palavras testar, verifique a nossa hierarquia atual:
          </p>
          <Link href="/hierarchies">
            <Button>
              Veja a hierarquia de palavras.
            </Button>
          </Link>
        </Container>
      </main>
    </>
  )
}

export default Home
